version: "3.1"

services:
  pgdb:
    image: postgres:alpine
    container_name: db-create-simple-be
    environment:
      - POSTGRES_DB=createsimplebe
      - POSTGRES_USER=createsimplebe
      - POSTGRES_PASSWORD=createsimplebe
    ports:
      - "5432:5432"
    volumes:
      - dbcreatesimplebe:/var/lib/postgresql/data/
volumes:
  dbcreatesimplebe:
